version: "3"
services: 
  web:
    container_name: web
    build: web
    volumes: 
      - ./web:/app/src
      - ./data/images:/app/images
    ports: 
        - 5000:5000
    command: flask run --host 0.0.0.0 --port 5000
    
